### ISSUE TITLE
Something to consider

### ISSUE THREAD

**Issue by uberhacker** [DinkumInteractive/mwu#8]
Hey @mustela: This looks like a really useful plugin!  Nice to see my project has provided a good foundation for you to build around.  There were a few lessons learned after I created the first iteration of the mcu plugin.  It looks like you may have forked my project in the early stages.  One thing you should definitely consider is letting the Pantheon migration workflow work for you instead of trying to update test and live environments.  I have limited the mcu plugin to the dev and multi-dev environments only for this very reason.  <code>Edit:  After examining the code further, I see you have an --auto-deploy option.  Probably should still update the --env argument to only allow dev or multi-dev environments because you wouldn't want to apply updates directly to live without performing updates and testing first, right?</code>

**Comment by mustela** [comment]
@uberhacker first of all, thanks for your plugin since it was the fundation of ours! 

About deploying into test/live, yes, you are right, and thought about it a lot, in fact at the very beginning it was working as you were saying, just deploying things to dev/mutidev.  But we have a long list of websites, and a lot more are coming (more than 100), this is why we added [the file feature](https://github.com/DinkumInteractive/mwu/blob/master/sites-demo.yml), so we need to automate deploys. 

We have tests running in most of them, so we can identify issues immediately and for others we are doing some manual testing. But we are working on automate testing and other ways of validating if the websites are running as they should, and make deployments base on those tests results. Hope we can have that really soon.
